# Site settings
title: Elmo Nemo
email: info@getelmo.org
url: https://github.com/thecartercenter/elmo
description: "ELMO NEMO data collection and analysis system"
keywords: "ODK, SMS, Data collection, election, observation"
skills: "A Robust Mobile Data Collection & Analysis System"
meta_author: The Carter Center

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: AEADA9 #F5A874 80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 6C89BC #FD6E8A
  secondary-dark: AFC2E0 #A2122F

# Footer settings
footer:
  copyright: The Carter Center

# Build settings
markdown: kramdown
permalink: pretty

# i18n
languages: ["en", "fr", "ar"]